apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base/db
  - ../../base/redis
  - ../../base/result
  - ../../base/worker
  - ../../base/vote

patches:
  - target:
      kind: Deployment
      name: vote
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - path: roll-out/patch-rollout-worker.yaml
    target:
      kind: Deployment
      name: worker
  - path: roll-out/patch-rollout-vote.yaml
    target:
      kind: Deployment
      name: vote
  - path: roll-out/patch-rollout-result.yaml
    target:
      kind: Deployment
      name: result
  - path: patch-storageclass-name.yaml
    target:
      kind: StorageClass
      name: gp3-prod 






      
images:
  - name: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/result
    newName: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/result
    newTag: a3a2e38e907d3ad24962301c8d576e813852db41
  - name: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/vote
    newName: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/vote
    newTag: e4f2363dd410dfdeec40dfe77c5d940440fcabae
  - name: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/worker
    newName: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/worker
    newTag: e01bbde0257c659fbfa9fbc25d6699f52a852a88
