apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-green

spec:
  replicas: 1

  selector:
    matchLabels:
      app: vote
      version: green

  template:
    metadata:
      labels:
        app: vote
        version: green

    spec:
      containers:
        - name: vote
          image: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/vote:1166d94d68106ba44bdea7f113b0e2be642586d5
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          env:
            - name: REDIS_HOST
              value: redis