apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-blue

spec:
  replicas: 1

  selector:
    matchLabels:
      app: vote
      version: blue

  template:
    metadata:
      labels:
        app: vote
        version: blue

    spec:
      containers:
        - name: vote
          image: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/vote:e5bd48f3d1780ef1553419d83ca496dbc7077315
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          env:
            - name: REDIS_HOST
              value: redis