apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base/storageclass
  - ../../base/db
  - ../../base/redis
  - ../../base/result
  - ../../base/worker

  - blue-green/deployment-blue-vote.yaml
  - blue-green/deployment-green-vote.yaml

  - blue-green/service-vote.yaml

patches:
  - path: ../dev/patch-imagepullsecret.yaml
    target:
      kind: Deployment

  - path: ../dev/patch-db-pvc.yaml
    target:
      kind: PersistentVolumeClaim
      name: db-pvc

  - path: ../dev/patch-redis-pvc.yaml
    target:
      kind: PersistentVolumeClaim
      name: redis-pvc

  - path: ../dev/roll-out/patch-rollout-result.yaml
    target:
      kind: Deployment
      name: result

  - path: ../dev/roll-out/patch-rollout-worker.yaml
    target:
      kind: Deployment
      name: worker

  # Wait for patching to change traffic to green
  # - path: blue-green/patch-switch-green.yaml
  #   target:
  #     kind: Service
  #     name: vote

