
 config:
  discord:
    webhookurl: "https://discord.com/api/webhooks/1515414420992561334/mNdYkGh65Kc-h3HbuMeuRtjYE1caEBcff0sYEeW-90Kbeb-oWGHmB5P9cJ2_L1b17fhv"

  customfields:
    cluster: eks-dev
    environment: prod
