apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base

images:
- name: hgyang25/result-app
  newName: hgyang25/result-app
  newTag: b5748f45cdf7b0abed0eea333e66571a664ef7fe
- name: hgyang25/vote-app
  newName: hgyang25/vote-app
  newTag: b5748f45cdf7b0abed0eea333e66571a664ef7fe
- name: hgyang25/worker-app
  newName: hgyang25/worker-app
  newTag: b5748f45cdf7b0abed0eea333e66571a664ef7fe
